### ISSUE TITLE
Add an option to have certain tokens ignore limits

### ISSUE THREAD

**Issue by Dukezilent** [dev7355608/limits#19]
I'm sorry if this feature is already available, but it didn't seem like there is one yet. Basically, I'm wondering if you could add a flag that allows a token to ignore/bypass all vision limits set by this module. This would allow me to create an active effect for various purposes. Thank you.

**Comment by dev7355608** [comment]
I don't think I'll add token-specific overrides/limits because the UI would have to be more complicated and I also don't want to use flags anymore or inject UI in the token config. It's pretty clean now with Region Behaviors. You could create a special detection mode that ignores the limit and give it to the tokens, but I admit that required advanced knowledge.
