### ISSUE TITLE
Global Illumination incorrectly reveals areas that limit light (only the area: tokens within it are not)

### ISSUE THREAD

**Issue by Tarbarian** [dev7355608/limits#3]
Foundry v11 307
Limits 0.1.0
libWrapper 1.12.13.0

In scenes with global illumination enabled light limits stop the light itself but do not prevent vision. They should override (or have the option to override) the global illumination of the scene.

Global Illumination On:
![image](https://github.com/dev7355608/limits/assets/76751079/1e7df447-094a-4821-9a26-2a248768f309)

Darkness Up, but Global Illumination On:
![image](https://github.com/dev7355608/limits/assets/76751079/760f172a-50d8-4316-8634-483ded64db0a)

Global Illumination Off:
![image](https://github.com/dev7355608/limits/assets/76751079/135c1f13-ba0d-491b-8299-bb15226db10a)

**Comment by dev7355608** [comment]
The global light won't have an effect regarding the visibility of tokens anymore in 1.0.0, but it's not possible to add holes into the shape of lights at the moment (maybe that will change in V12). So the space is illuminated, but it won't reveal tokens.

There's also the question where the global light originates from, which is important for the ray casting that is done. Does it originate from multiple points in the scene, or is parallel rays coming in from above? Both could be true: a cave illuminated by glowing mushrooms or sunlight.

**Comment by rapus95** [comment]
@Tarbarian While trying to differentiate this error from mine (#16) I'm getting confused, because the only image where "only the area [is revealed]: tokens within are not [revealed]" is the one without global illumination which then wouldn't fit the issue description. Till now I thought the error was on the global illumination on, darkness up, image. But at the same time, that image looks correct, assuming global illumination to be dim light and penetrating the limits area, thus every point in the limited area is dim light. And since you didn't limit light perception, every "dim light"-lit point can be seen as usual by ordinary light perception. So to me, right now, all images look correct. (the Global illumination off image looks like it just shows revealed fog of war)

**Comment by dev7355608** [comment]
> The global light won't have an effect regarding the visibility of tokens anymore in 1.0.0, but it's not possible to add holes into the shape of lights at the moment (maybe that will change in V12). So the space is illuminated, but it won't reveal tokens.

I reverted this behavior in 1.1.0 (https://github.com/dev7355608/limits/releases/tag/v1.1.0). Global Illumination is no longer affected by light limits.

Closing this issue for now, but will reconsider the behavior as Global Illumination evolves.
