### ISSUE TITLE
Sequencer Template Effects Not Visible

### ISSUE THREAD

**Issue by txm3278** [dev7355608/limits#6]
Is there a way to allow sequencer effects added to templates (like darkness or fog cloud) to be visible to tokens that can not see into the template?

**Comment by dev7355608** [comment]
I'm not sure if Sequencer allows rendering the effect above the fog of war. That wouldn't be something Limits has control over. I recommend increasing the scale of the effect so that you can tell what's obstructing vision:

![image](https://github.com/dev7355608/perfect-vision/assets/31905376/cc5d4452-b996-4275-a377-8a34118b2828)

**Comment by YenBenGrey** [comment]
If you go on to the settings of a template there is an option in there for Token FX if you have the module of course. 
When you choose the type of special effect it appears above the template and you can see it. 
I have been trying today with no luck because I don't have the skills to try and include token magic fx in the macro for darkness. 

I have been able to set the fillColor: null, (that way you don't get the template squares appear when you hover)

**Comment by dev7355608** [comment]
@YenBenGrey I can add TMFX effects to the example macros maybe later today.

@txm3278 If you have a Sequencer macro for Darkness / Fog Cloud, don't hesitate to share it. I'd like to add Sequencer effects to the example macros.

**Comment by YenBenGrey** [comment]
> @YenBenGrey I can add TMFX effects to the example macros maybe later today.

It is ok, ignore my request, with the help of Thatlonelybugbear the template is now part of the spell and if the FX is on, and it bends round walls the person in the Darkness can see the shape of the room/corridor/space they are in if it is confined. Therefore please ignore my request.

**Comment by txm3278** [comment]
I use the 5e Animations module to handle sequencer so don't have anything specific to add. We did figure out that TMFX textures are fully visible while also being blocked by normal walls so that seems like the way to go
