### ISSUE TITLE
New Macros

### ISSUE THREAD

**Issue by YenBenGrey** [dev7355608/limits#7]
Just want to say the new macros are awesome and fantastic.
I have been able to change the fillColor to null so that you don't get the square template when you hover. 

However when the spell ends it doesn't go away automatically. 

I am using ItemMacro and MidiQol-Qol to trigger the template. 

Is there another way to add the template to the spell other than ItemMacro or MidiQol?

If there is Token Magic FX has a setting where you can add the special effects to a specific named Spell. But because the spell is using the macro instead of its own template it isn't being added. :-(

**Comment by dev7355608** [comment]
> However when the spell ends it doesn't go away automatically.

What is "it": the template or just the vision limitation? If the vision limitation doesn't go away when the template is deleted that would be a bug. Otherwise deleting the template would be the responsibility of another module.

I'm not an expect in the area of Midi and other automation modules. The people hanging out in #macro-polo probably know more about this than me. The Midi experts you find in [this](https://discord.com/channels/170995199584108546/1010273821401555087) channel.

It is possible to automatically add the the limits when the spell is cast with a world script (or a separate module) without a dependency on another module.
